### PR TITLE
VkspReflection non-sematic: remove literals for Ids

### PR DESCRIPTION
**Pull request by rjodinchr**
https://gitlab.khronos.org/spirv/SPIR-V/-/issues/817

### CODE REVIEW

**Comment by rjodinchr** [comment]
@spencer-lunarg PTAL

**Review by Naghasan — APPROVED** [review]

**Review by spencer-lunarg — APPROVED** [review]
LGTM - when this lands will update https://github.com/KhronosGroup/SPIRV-Visualizer to parse these as well

**Comment by alan-baker** [comment]
Merging this to facilitate tooling updates.

**Comment by spencer-lunarg** [comment]
adding reference to original PR incase someone else find that PR first

https://github.com/KhronosGroup/SPIRV-Headers/pull/398

**Pull request merged**
