### PR TITLE
MeshShadingNV enables builtins PrimitiveId, Layer, and ViewportIndex

### LINKED ISSUE #179: builtins such as PrimitiveId should be enabled by MeshShadingNV
[SPV_NV_mesh_shader](https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_mesh_shader.asciidoc) says that a number of builtins, including PrimitiveId should be enabled by the MeshShadingNV capability.

This is missing from the grammar.  

It's blocking me from landing a fix to Glslang.   https://github.com/KhronosGroup/glslang/issues/2461

### PR DESCRIPTION
**Pull request by dneto0**
Fixes #179

See extension SPV_NV_mesh_shader

### CODE REVIEW

**Comment by dneto0** [comment]
cc: @dgkoch

**Comment by dneto0** [comment]
Easy-to-read [SPV_NV_mesh_shader](https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_mesh_shader.asciidoc)

**Review by dgkoch — APPROVED** [review]
LGTM

**Comment by dgkoch** [comment]
A version of SPV_NV_mesh_shader that actually shows everything: http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_mesh_shader.html

**Pull request merged**
