### PR TITLE
Report failures in makeHeaders

### PR DESCRIPTION
**Pull request by kpet**
Exit the script when one of the called command fails.

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]

**Comment by johnkslang** [comment]
It looks like we have a `LiteralFloat` in the grammar file, from June 21st that should be fixed, regarding `FPMaxErrorDecorationINTEL`.

@bashbaug

**Comment by bashbaug** [comment]
This should be good now that we have reverted the `LiteralFloat` changes, but if we want to be sure we can rebase this PR and these tests should pass.

**Comment by kpet** [comment]
@bashbaug I've rebased the change. I agree it would be good to see it pass now that we've validated that it does enable the CI to fail when there are generation issues.

**Comment by bashbaug** [comment]
CI is clean and there are two approvals.  Merging.

**Pull request merged**
