### PR TITLE
ClspvReflection non-sematic: add NormalizedSamplerMaskPushConstant

### PR DESCRIPTION
**Pull request by rjodinchr**
This is needed to implement 3D Image read using unnormalised sampler.

Ref google/clspv#1202

### CODE REVIEW

**Comment by rjodinchr** [comment]
@alan-baker , could you review this PR?
Thanks

**Review by kpet — APPROVED** [review]
LGTM. @rjodinchr Have you prepared an update to the specification? I couldn't find the PR.

**Comment by rjodinchr** [comment]
> LGTM. @rjodinchr Have you prepared an update to the specification? I couldn't find the PR.

I did not update the specification. What repository is it in?

**Comment by alan-baker** [comment]
> > LGTM. @rjodinchr Have you prepared an update to the specification? I couldn't find the PR.
> 
> I did not update the specification. What repository is it in?

https://github.com/KhronosGroup/SPIRV-Registry

**Review by alan-baker — APPROVED** [review]

**Comment by rjodinchr** [comment]
I have created https://github.com/KhronosGroup/SPIRV-Registry/pull/220

**Pull request merged**
