### PR TITLE
Add SPIR-V tokens that related with AMD extensions

### PR DESCRIPTION
**Pull request by amdrexu**

### CODE REVIEW

**Comment by amdrexu** [comment]
As we discussed, please help me to add those tokens to SPIR-V headers and propagate them to all SPIR-V versions. Thank you very much.

**Comment by johnkslang** [comment]
This is now applied internally in the Khronos source. Changes to this file and headers, etc., will show up next time headers are updated.

**Comment by amdrexu** [comment]
Thanks for your kind help.

**Comment by johnkslang** [comment]
Note that many of the final entries in lists added ended with `,` and that is not legal according to the JSON processor SPIR-V is using.

**Pull request closed without merging**
