### PR TITLE
Update SPV_AMDX_shader_enqueue

### PR DESCRIPTION
**Pull request by yavn**
Headers modifications for the SPIR-V change: https://github.com/KhronosGroup/SPIRV-Registry/pull/286

### CODE REVIEW

**Review by Naghasan — APPROVED** [review]
LGTM, there is 2 small discrepancy between the text and grammar but I suspect it is the text being out of sync

**Comment by Tobski** [comment]
> LGTM, there is 2 small discrepancy between the text and grammar but I suspect it is the text being out of sync

Yep, now fixed in the spec. Thanks!

**Comment by y-novikov** [comment]
Is there a corresponding PR for https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/vulkan/generated/spirv_grammar_helper.cpp#L720?

**Comment by y-novikov** [comment]
Looks like this is being worked on in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8679

**Pull request merged**
