### PR TITLE
Clay is an internal framework of Tellusim Technologies Inc.

### PR DESCRIPTION
**Pull request by clayengine**
Please merge our updated information.

### CODE REVIEW

**Comment by clayengine** [comment]
Please merge our updated information. CLA is signed, but the status is not getting updated.

**Comment by clayengine** [comment]
"You have agreed to the CLA for KhronosGroup/SPIRV-Headers" and nothing after that.

**Comment by clayengine** [comment]
"Thank you clayengine for signing the CLA! we are now taking you back to GitHub"
The Contributor License Agreement is still not working.

**Comment by kpet** [comment]
@outofcontrol It looks like there is an issue with the CLA check. Could you take a look please?

**Comment by clayengine** [comment]
Signed. That was weird.

**Comment by outofcontrol** [comment]
Always nice when it is a simple fix :) Have a great weekend everyone!

**Pull request merged**
